# workflow 이름(Github Actions 하나의 과정, 단위) - 하나의 yml 파일이 하나의 workflow
name: Github Actions 실행시켜보기

# Event : 실행되는 시점을 설정 - 어느 시점에 Github Actions를 실행시키고 싶은지?
# -> main이라는 브랜치에 push가 되면 Github Actions 로직을 실행시키겠다.
on:
  push:
    braches:
      - main

# 하나의 workflow는 1개 이상의 job으로 구성된다. - 하나의 workflow에 여러 개의 job 가능
# 여러 job은 기본적으로 병렬적으로 수행된다.
jobs:
  # job을 식별하기 위한 id
  My-Deploy-Job:
    # ubuntu 환경
    runs-on: ubuntu-latest

    # 특정 작업을 수행하는 가장 작은 단위
    # job은 여러 step들로 구성되어 있다.
    steps: # step마다 이름 붙이고, 리눅스 명령어를 run으로 작성
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"